In [1]:
#Lab Tasks
#list
xs = [1,2,3,4]
print(xs, xs[1])
print(xs[-1])

[1, 2, 3, 4] 2
4


In [2]:
#Slicing
nums = list(range(5))
print(nums)
print(nums[2:4])

[0, 1, 2, 3, 4]
[2, 3]


In [3]:
#animals
animals = ["dog", "Cat", "Goat"]
for animal in animals:
    print(animal)

dog
Cat
Goat


In [4]:
#using enumerate function
animals = ["dog", "Cat", "Goat"]
for idx, animal in enumerate(animals):
    print(idx + 1, animal)

1 dog
2 Cat
3 Goat


In [5]:
#List comprehensions
nums = [1,2,3,4,5]
squ = []

for x in nums:
    squ.append(x**2)
    print(squ)

[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]
[1, 4, 9, 16, 25]


In [6]:
#dictionaries
d = {'Cat' : 'Cute', 'Dog' : 'Furry', 'Atif' : 'Dangi'}
print(d['Cat'],"--", d['Dog'],"--", d['Atif'])

Cute -- Furry -- Dangi


In [7]:
#Sets
animals = ['cat', 'dog', 'goat', 'snake']
print('cat' in animals) #true
print('Atif' in animals) # false
print('goat' in animals)
print('fish' in animals)
print(len(animals))

True
False
True
False
4


In [8]:
#tuples
d = {(x, x+1): x for x in range(10)}
t = (5,6)
print(type(t))
print(d[t])
print(d[(1,2)])

<class 'tuple'>
5
1


In [9]:
#function
def sign(x):
    if x > 0:
        return 'Positive'
    elif x < 0:
        return 'Negative'
    else:
        return 'Zero'

for x in [-1, 0, 1]:
    print(sign(x))

Negative
Zero
Positive


In [10]:
#classes
class Greeter(object):

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


In [18]:
#Numpy library
import numpy as np
a = np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
#change the element of array
a[0] = 5
print(a)

b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], [1,0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 [1, 0]


In [20]:
#Data types
import numpy as np
x = np.array([1,2])
print(x.dtype)

x = np.array([1.2, 2.2])
print(x.dtype)

int32
float64


In [21]:
#Broadcasting
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v


print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
