In [1]:
x = [1,2,3,4,5,6]
print(x)
print(type(x))
print(x[1])
print(len(x))

[1, 2, 3, 4, 5, 6]
<class 'list'>
2
6


In [10]:
x.append(66)
print(x)

[1, 2, 3, 4, 5, 6, 66]


In [11]:
x.insert(0, 100) # used to add any index
print(x)

[100, 1, 2, 3, 4, 5, 6, 66]


In [20]:
z=[[22,33,44],[77,88,99,100]]


In [21]:
print(z)

[[22, 33, 44], [77, 88, 99, 100]]


In [22]:
print(z[1][0])

77


In [23]:
print(z[0][2])

44


In [24]:
print(z[1][0])

77


In [25]:
z.append([201,202,203])

In [26]:
print(z)

[[22, 33, 44], [77, 88, 99, 100], [201, 202, 203]]


In [27]:
z.insert(2,[204,205,206])

In [28]:
print(z)

[[22, 33, 44], [77, 88, 99, 100], [204, 205, 206], [201, 202, 203]]


In [30]:
#If I want a 206 how I can access lets see
print(z[2][2])

206


In [35]:
z.pop([1][0])


[77, 88, 99, 100]

In [36]:
print(z)

[[22, 33, 44], [204, 205, 206], [201, 202, 203]]


In [46]:
s = int(input())
t = int(input())
u = s*t
print(u)

2
3
6


In [50]:
import numpy as np
b = np.array(z)
print(b)

[[ 22  33  44]
 [204 205 206]
 [201 202 203]]


In [51]:
print(type(b))

<class 'numpy.ndarray'>


In [52]:
print(b.ndim)

2


In [53]:
print(b*b)

[[  484  1089  1936]
 [41616 42025 42436]
 [40401 40804 41209]]
